<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ConvergePaymentsGateway\Model;

use ConvergePaymentsGateway\Model\Base\ConvergePayments as BaseConvergePayments;

/**
 * Class ConvergePayments
 * @package ConvergePaymentsGateway\Model
 */
class ConvergePayments extends BaseConvergePayments
{
}
