<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ConvergePayments\Action;

use ConvergePayments\Action\Base\ConvergePaymentsAction as  BaseConvergePaymentsAction;

/**
 * Class ConvergePaymentsAction
 * @package ConvergePayments\Action
 */
class ConvergePaymentsAction extends BaseConvergePaymentsAction
{
}
