<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ConvergePayments\Event\Module\Base;

/**
 * Class ConvergePaymentsEvents
 * @package ConvergePayments\Event\Module\Base
 * @author TheliaStudio
 */
class ConvergePaymentsEvents
{
    const CONVERGE_PAYMENTS_CREATE = "action.converge_payments.create";
    const CONVERGE_PAYMENTS_UPDATE = "action.converge_payments.update";
    const CONVERGE_PAYMENTS_DELETE = "action.converge_payments.delete";
}
