<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ConvergePayments\Event;

use ConvergePayments\Event\Base\ConvergePaymentsEvent as BaseConvergePaymentsEvent;

/**
 * Class ConvergePaymentsEvent
 * @package ConvergePayments\Event
 */
class ConvergePaymentsEvent extends BaseConvergePaymentsEvent
{
}
