<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ConvergePayments\Event;

use ConvergePayments\Event\Base\ConvergePaymentsEvents as BaseConvergePaymentsEvents;

/**
 * Class ConvergePaymentsEvents
 * @package ConvergePayments\Event
 */
class ConvergePaymentsEvents extends BaseConvergePaymentsEvents
{
}
