<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ConvergePaymentsGateway\Loop;

use ConvergePaymentsGateway\Loop\Base\ConvergePayments as BaseConvergePaymentsLoop;

/**
 * Class ConvergePayments
 * @package ConvergePaymentsGateway\Loop
 */
class ConvergePayments extends BaseConvergePaymentsLoop
{
    /**
     * You may now add your own logic
     */
}
