<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ConvergePayments\Event\Module;

use ConvergePayments\Event\Module\Base\ConvergePaymentsEvents as BaseConvergePaymentsEvents;

/**
 * Class ConvergePaymentsEvents
 * @package ConvergePayments\Event\Module
 * @author TheliaStudio
 */
class ConvergePaymentsEvents extends BaseConvergePaymentsEvents
{
}
