<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ConvergePayments\Event\Base;

use ConvergePayments\Event\Module\ConvergePaymentsEvents as ChildConvergePaymentsEvents;

/*
 * Class ConvergePaymentsEvents
 * @package ConvergePayments\Event\Base
 * @author TheliaStudio
 */
class ConvergePaymentsEvents
{
    const CREATE = ChildConvergePaymentsEvents::CONVERGE_PAYMENTS_CREATE;
    const UPDATE = ChildConvergePaymentsEvents::CONVERGE_PAYMENTS_UPDATE;
    const DELETE = ChildConvergePaymentsEvents::CONVERGE_PAYMENTS_DELETE;
}
