<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ConvergePayments\Event\Base;

use Thelia\Core\Event\ActionEvent;
use ConvergePayments\Model\ConvergePayments;

/**
* Class ConvergePaymentsEvent
* @package ConvergePayments\Event\Base
* @author TheliaStudio
*/
class ConvergePaymentsEvent extends ActionEvent
{
    protected $id;
    protected $orderId;
    protected $messageId;
    protected $message;
    protected $convergePayments;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getOrderId()
    {
        return $this->orderId;
    }

    public function setOrderId($orderId)
    {
        $this->orderId = $orderId;

        return $this;
    }

    public function getMessageId()
    {
        return $this->messageId;
    }

    public function setMessageId($messageId)
    {
        $this->messageId = $messageId;

        return $this;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage($message)
    {
        $this->message = $message;

        return $this;
    }

    public function getConvergePayments()
    {
        return $this->convergePayments;
    }

    public function setConvergePayments(ConvergePayments $convergePayments)
    {
        $this->convergePayments = $convergePayments;

        return $this;
    }
}
