<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ConvergePayments\Action\Base;

use ConvergePayments\Model\Map\ConvergePaymentsTableMap;
use ConvergePayments\Event\ConvergePaymentsEvent;
use ConvergePayments\Event\ConvergePaymentsEvents;
use ConvergePayments\Model\ConvergePaymentsQuery;
use ConvergePayments\Model\ConvergePayments;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use \Thelia\Core\Event\TheliaFormEvent;

/**
 * Class ConvergePaymentsAction
 * @package ConvergePayments\Action
 * @author TheliaStudio
 */
class ConvergePaymentsAction extends BaseAction implements EventSubscriberInterface
{
    public function create(ConvergePaymentsEvent $event)
    {
        $this->createOrUpdate($event, new ConvergePayments());
    }

    public function update(ConvergePaymentsEvent $event)
    {
        $model = $this->getConvergePayments($event);

        $this->createOrUpdate($event, $model);
    }

    public function delete(ConvergePaymentsEvent $event)
    {
        $this->getConvergePayments($event)->delete();
    }

    protected function createOrUpdate(ConvergePaymentsEvent $event, ConvergePayments $model)
    {
        $con = Propel::getConnection(ConvergePaymentsTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $orderId = $event->getOrderId()) {
                $model->setOrderId($orderId);
            }

            if (null !== $messageId = $event->getMessageId()) {
                $model->setMessageId($messageId);
            }

            if (null !== $message = $event->getMessage()) {
                $model->setMessage($message);
            }

            $model->save($con);

            $con->commit();
        } catch (\Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setConvergePayments($model);
    }

    protected function getConvergePayments(ConvergePaymentsEvent $event)
    {
        $model = ConvergePaymentsQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'converge_payments' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents()
    {
        return array(
            ConvergePaymentsEvents::CREATE => array("create", 128),
            ConvergePaymentsEvents::UPDATE => array("update", 128),
            ConvergePaymentsEvents::DELETE => array("delete", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".converge_payments_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".converge_payments_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".converge_payments_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".converge_payments_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
